// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "SvU(Jm7DhCe%D%N=ZLak":
            case "steve":return img`
..................
..................
..................
..................
......eeeeee......
......eeedfd......
......eddddd......
......ddffdd......
......dffffd......
......dddddd......
242222822228222422
222222822228222222
2222428222282422dd
ddd22282222822dddd
dddd2282422822dddd
dddd2282222822dddd
dddd8888888888dddd
dddd8888888888dddd
dddd8888888688dddd
dddd8688888888dddd
dddd8888888888dddd
dddd8888886888dddd
....8868888886....
....688....688....
....d88....d88....
....ddd....ddd....
....ddd....ddd....
....ffd....ffd....
....ffff...ffff...
....ffff...ffff...
`;
            case "|-DfPITv=Ow(0o]Fp:vi":
            case "mouse button":return img`
. . . . . . . . . . . . . . . . 
. . . . . . 1 1 . . . . . . . . 
. . . . . 1 f f 1 . . . . . . . 
. . . . . 1 f f f 1 . . . . . . 
. . . . . 1 f f f f 1 . . . . . 
. . . . . . 1 f f f f 1 . . . . 
. . . . . . . 1 f f f f 1 . . . 
. . . . . . . 1 f f f 1 . . . . 
. . . . . . . . 1 f 1 . . . . . 
. . . . . . . . . 1 . 1 . . . . 
. . . . . . . . . . . . 1 . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case ";W{{az($5q]Boj??dGeY":
            case "picture":return img`
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
`;
            case ")Yr]^RWi=[qFYga~pLyl":
            case "grim reeper":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "uJQ_]NRE#(!%#xRoS`lO":
            case "duck":return img`
. . . . . . . . . . b 5 b . . . 
. . . . . . . . . b 5 b . . . . 
. . . . . . . . . b c . . . . . 
. . . . . . b b b b b b . . . . 
. . . . . b b 5 5 5 5 5 b . . . 
. . . . b b 5 d 1 f 5 5 d f . . 
. . . . b 5 5 1 f f 5 d 4 c . . 
. . . . b 5 5 d f b d d 4 4 . . 
b d d d b b d 5 5 5 4 4 4 4 4 b 
b b d 5 5 5 b 5 5 4 4 4 4 4 b . 
b d c 5 5 5 5 d 5 5 5 5 5 b . . 
c d d c d 5 5 b 5 5 5 5 5 5 b . 
c b d d c c b 5 5 5 5 5 5 5 b . 
. c d d d d d d 5 5 5 5 5 d b . 
. . c b d d d d d 5 5 5 b b . . 
. . . c c c c c c c c b b . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
